title: 工程师与技术的日常

# 自定义post url
permalink: /:year/:month/:day/:title
timezone: Asia/Shanghai

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  extensions:
    - autolink
    - footnotes
    - smart

hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
plugins:
  - jekyll-sitemap

production_url: https://lanffy.github.io
github_url: https://github.com/lanffy
weibo_url: http://weibo.com/raoliang
#theme: jekyll-theme-cayman
